const express = require("express")
const app = express()
const cors = require("cors")
app.use(cors())

app.use(express.json())


const simpleRoute = require("./routes/simpleRoute")
app.use("/", simpleRoute)

const token = {
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2VFpEYnNQeURDcWw3cExrQ1YtVVRjZXdjbFV4Z05lSXczVWQyNlJZOHJZIn0.eyJleHAiOjE2ODIzNDA1MjQsImlhdCI6MTY4MjM0MDIyNCwianRpIjoiNzllN2NmZmItZTZkOS00MTFhLWFjMzYtYjhiNTk2MTNmNDg1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vLXJlYWxtIiwiYXVkIjpbImV4cHJlc3MtYXBwIiwiYWNjb3VudCJdLCJzdWIiOiIxNzllYTFiMy1iOWU4LTQ2N2QtYmZiMy05ODJhZTU0NWU5MjYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJleHByZXNzLWFwcCIsInNlc3Npb25fc3RhdGUiOiI0NmE3NmIzZC0xNzhjLTRhYjgtOTE1Zi1hZjlkNGNiYmI5YmMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtZGVtby1yZWFsbSIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJyb2xlLW1hcHBpbmcgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjQ2YTc2YjNkLTE3OGMtNGFiOC05MTVmLWFmOWQ0Y2JiYjliYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoicmVndWxhci11c2VyIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.cQf8QN8GlcGTGWI23Jx2_iRMo_YOFJECNuoI7hHb6dcsnj4PP9WluMOidYs7BSVz2tMkvCSSeC1SksqQm9AwIa513mVRlSXn0KNaRiuGebzlSmkVhLPmcXTELUzVV0EZ5QPS8Ss0LqMBDK9H4oBnK7rHlee2JRDXdDRxA08KqK9bytV3DmucTnoZRDeypNdVliI9LhlIQl-OMiNBX_JohAeoolBgA_7EhIqyVAsxX8eZlACxIMIm8tdgLflU7UaiBny9ly-L-SE6iDnmGpAKl9wXOrvYXCCoIg2KamdH5XsFT5msJS5DQDeIcbUObVHdfC4ulbgpOkrK9Ipkm_n_Og",
    "expires_in": 300,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1NDAwZmMwMi1lNzE1LTRlZmItODRlYy0yZjU4OGEzMTc0YmQifQ.eyJleHAiOjE2ODIzNDIwMjQsImlhdCI6MTY4MjM0MDIyNCwianRpIjoiMjI2M2ZjYmUtMzYyMS00NGEzLTg4YzQtNTNmYTFiNjVhM2IyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vLXJlYWxtIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vLXJlYWxtIiwic3ViIjoiMTc5ZWExYjMtYjllOC00NjdkLWJmYjMtOTgyYWU1NDVlOTI2IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImV4cHJlc3MtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjQ2YTc2YjNkLTE3OGMtNGFiOC05MTVmLWFmOWQ0Y2JiYjliYyIsInNjb3BlIjoicm9sZS1tYXBwaW5nIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI0NmE3NmIzZC0xNzhjLTRhYjgtOTE1Zi1hZjlkNGNiYmI5YmMifQ.LuQGRsjmV3zTWEAriQPX-IsWoqJyKlYQHZo9eXuYMXI",
    "token_type": "Bearer",
    "not-before-policy": 0,
    "session_state": "46a76b3d-178c-4ab8-915f-af9d4cbbb9bc",
    "scope": "role-mapping profile email"
}




const port = process.env.PORT || 5000
app.listen(port, () => {
    console.log(`API server listening at http://localhost:${port}`)
})